version: '3.1'
services:
  nginx:
    image: nginx:1.21
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - redmine
    volumes:
      - statics:/usr/src/redmine/public
  redmine:
    build:
      context: ./redmine
      dockerfile: Dockerfile
      args:
        - REDMINE_PATH=${REDMINE_PATH}
    restart: always
    expose:
      - 3000
    volumes:
      - redmine_uploads:/usr/src/redmine/files
      - statics:/usr/src/redmine/public
    env_file:
      - .env.production
  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backups:/backups
      - redmine_uploads:/files

volumes:
  redmine_uploads:
    driver: local
  statics:

