version: '3.1'
services:
  nginx:
    image: nginx:1.21
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 3000:3000
    depends_on:
      - redmine
    volumes:
      - statics:/usr/src/redmine/public
      - puma:/usr/src/redmine/tmp
  redmine:
    build:
      context: ./redmine
      dockerfile: Dockerfile
      args:
        - DB_HOST=${DB_HOST}
        - REDMINE_DB_DATABASE=${REDMINE_DB_DATABASE}
        - REDMINE_DB_PASSWORD=${REDMINE_DB_PASSWORD}
        - REDMINE_DB_USERNAME=${REDMINE_DB_USERNAME}
        - REDMINE_PATH=${REDMINE_PATH}
        - REDMINE_VERSION=${REDMINE_VERSION}
        - RAILS_ENV=${RAILS_ENV}
    restart: always
    expose:
      - 3000
    volumes:
      - ./redmine/redmine_uploads:/usr/src/redmine/files
      - statics:/usr/src/redmine/public
      - puma:/usr/src/redmine/tmp
  #backup?
volumes:
  statics:
  puma:
