version: '3.1'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - redmine
    volumes:
      - statics:/usr/src/redmine/public
  redmine: &redmine-template
    build:
      context: ./redmine
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 3000
    volumes:
      - redmine_uploads:/usr/src/redmine/files
      - statics:/usr/src/redmine/public
    network_mode: service:nginx
    env_file:
      - .env
  migrations: 
    <<: *redmine-template
    command: ["bundle", "exec", "rake", "db:migrate"]
  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./backups:/backups
      - redmine_uploads:/files

volumes:
  redmine_uploads:
    driver: local
  statics:

