development:
  adapter: mysql2
  database: <%= ENV["REDMINE_DB_DATABASE"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["REDMINE_DB_USERNAME"] %>
  password: <%= ENV["REDMINE_DB_PASSWORD"] %>
  socket: /run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: <%= ENV["REDMINE_DB_DATABASE"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["REDMINE_DB_USERNAME"] %>
  password: <%= ENV["REDMINE_DB_PASSWORD"] %>
  socket: /run/mysqld/mysqld.sock