development:
  adapter: mysql2
  database: ${REDMINE_DB_DATABASE}
  host: ${DB_HOST}
  username: ${REDMINE_DB_USERNAME}
  password: ${REDMINE_DB_PASSWORD}

production:
  adapter: mysql2
  database: ${REDMINE_DB_DATABASE}
  host: ${DB_HOST}
  username: ${REDMINE_DB_USERNAME}
  password: ${REDMINE_DB_PASSWORD}